# Generated by Django 6.0.6 on 2026-08-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('campaign_update', 'Campaign update'), ('fund_utilization', 'Fund utilization report'), ('campaign_approved', 'Campaign approved'), ('campaign_rejected', 'Campaign rejected'), ('payment_verified', 'Payment verified'), ('payment_rejected', 'Payment rejected')], max_length=32),
        ),
    ]
