# Generated by Django 4.2.27 on 2026-08-10

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaigns", "0003_campaignupdate"),
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoPayment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("kbzpay", "KBZPay"), ("wave", "Wave Money"), ("mmqr", "MMQR (any supported wallet)")], max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("1.00"))])),
                ("message", models.CharField(blank=True, max_length=280)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("paid", "Demo payment completed"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="demo_payments", to="campaigns.campaign")),
                ("donation", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="demo_payment", to="donations.donation")),
                ("donor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="demo_payments", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
