# Generated by Django 4.2.27 on 2026-08-10

from django.db import migrations, models
from django.utils import timezone
from datetime import timedelta
from uuid import uuid4


def populate_demo_payment_details(apps, schema_editor):
    DemoPayment = apps.get_model("donations", "DemoPayment")
    for payment in DemoPayment.objects.filter(transaction_reference__isnull=True):
        payment.transaction_reference = f"GIV-{timezone.now():%Y%m%d}-{uuid4().hex[:6].upper()}"
        payment.expires_at = payment.created_at + timedelta(minutes=5)
        payment.save(update_fields=["transaction_reference", "expires_at"])


class Migration(migrations.Migration):

    dependencies = [("donations", "0002_demopayment")]

    operations = [
        migrations.AddField(
            model_name="demopayment",
            name="transaction_reference",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="demopayment",
            name="failure_reason",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="demopayment",
            name="expires_at",
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(populate_demo_payment_details, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="demopayment",
            name="transaction_reference",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="demopayment",
            name="status",
            field=models.CharField(choices=[("pending", "Pending"), ("paid", "Demo payment completed"), ("cancelled", "Cancelled"), ("failed", "Failed"), ("expired", "Expired")], default="pending", max_length=20),
        ),
    ]
