# Generated by Django 6.0.6 on 2026-08-26 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_demopayment_checkout_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demopayment',
            name='proof_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demopayment',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='donation-receipts/'),
        ),
        migrations.AddField(
            model_name='demopayment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demopayment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_payments_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demopayment',
            name='wallet_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='demopayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting payment proof'), ('submitted', 'Pending verification'), ('paid', 'Verified'), ('cancelled', 'Cancelled'), ('failed', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
