


import React, { useState } from "react";
import { BotIcon, SendIcon, SparklesIcon } from "lucide-react";
import { PageHeader } from "../../components/ui/PageHeader";
import { DemoNotice } from "../../components/ui/DemoNotice";
import { inputClass } from "../../components/ui/Field";

type ChatMessage = {id: string;role: "assistant" | "user";text: string;};

const seed: ChatMessage[] = [
{ id: "m1", role: "assistant", text: "Hi! I can help you understand where donations go, find verified campaigns, or locate a report. What would you like to know?" },
{ id: "m2", role: "user", text: "How much of my donation reaches programs?" },
{ id: "m3", role: "assistant", text: "Across all Givera campaigns, 94.2% of funds are allocated directly to programs. Each campaign also publishes its own allocation ratio and audit record — for example, Coastal Flood Response 2026 is at 81% allocated (ref. CMP-26-041)." }];


const suggestions = ["Show me urgent disaster campaigns", "Where can I download the 2026 annual report?", "What is your average program allocation?"];

export function Assistant() {
  const [messages, setMessages] = useState<ChatMessage[]>(seed);
  const [draft, setDraft] = useState("");

  function send(text: string) {
    if (!text.trim()) return;
    setMessages((prev) => [
    ...prev,
    { id: `u-${Date.now()}`, role: "user", text },
    { id: `a-${Date.now()}`, role: "assistant", text: "This is a demonstration assistant. In a live version I’d answer using Givera’s public records and campaign data with cited references." }]
    );
    setDraft("");
  }

  return (
    <div className="mx-auto flex w-full max-w-3xl flex-col px-4 py-8 sm:px-6">
      <PageHeader eyebrow="Support" title="Giving assistant" description="Ask about campaigns, allocations, and public reports." />
      <div className="mt-5"><DemoNotice>This assistant is a static demonstration. Responses are illustrative and not generated by a live model.</DemoNotice></div>

      <div className="mt-5 flex-1 space-y-4 rounded-lg border border-[#d8d8d2] bg-white p-5">
        {messages.map((m) =>
        <div key={m.id} className={`flex gap-3 ${m.role === "user" ? "flex-row-reverse" : ""}`}>
            <span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full ${m.role === "assistant" ? "bg-[#f0f8f4] text-[#16734e]" : "bg-[#eef2f6] text-[#3d5670]"}`}>
              {m.role === "assistant" ? <BotIcon className="h-4 w-4" aria-hidden="true" /> : <span className="text-[11px] font-bold">You</span>}
            </span>
            <div className={`max-w-[80%] rounded-lg px-3.5 py-2.5 text-[13px] leading-5 ${m.role === "assistant" ? "bg-[#f6f6f3] text-[#2b332e]" : "bg-[#16734e] text-white"}`}>
              {m.text}
            </div>
          </div>
        )}
      </div>

      <div className="mt-4 flex flex-wrap gap-2">
        {suggestions.map((s) =>
        <button key={s} type="button" onClick={() => send(s)} className="inline-flex items-center gap-1.5 rounded-full border border-[#cfd1ca] bg-white px-3 py-1.5 text-[12px] font-medium text-[#4a504a] transition-colors hover:bg-[#f5f6f3] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#16734e]">
            <SparklesIcon className="h-3.5 w-3.5 text-[#16734e]" aria-hidden="true" /> {s}
          </button>
        )}
      </div>

      <form className="mt-4 flex gap-2" onSubmit={(e) => {e.preventDefault();send(draft);}}>
        <input value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Ask a question…" aria-label="Message" className={inputClass} />
        <button type="submit" className="inline-flex shrink-0 items-center gap-2 rounded-md bg-[#16734e] px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-[#125f40] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#16734e]">
          <SendIcon className="h-4 w-4" aria-hidden="true" /> Send
        </button>
      </form>
    </div>);

}