# Generated by Django 6.0.6 on 2026-07-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/'),
        ),
    ]
