# Generated by Django 4.2.27 on 2026-08-13

from decimal import Decimal
import django.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaigns", "0003_campaignupdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundUtilization",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(max_length=2000)),
                ("amount_spent", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("1.00"))])),
                ("spent_on", models.DateField()),
                ("evidence", models.ImageField(blank=True, null=True, upload_to="fund-utilization/")),
                ("status", models.CharField(choices=[("pending", "Pending review"), ("approved", "Published"), ("rejected", "Needs changes")], default="pending", max_length=20)),
                ("review_note", models.CharField(blank=True, max_length=500)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fund_utilizations", to="campaigns.campaign")),
                ("submitted_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fund_utilizations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-spent_on", "-created_at"]},
        ),
    ]
