# Generated by Django 6.0.6 on 2026-08-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaignmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmedia',
            name='purpose',
            field=models.CharField(choices=[('gallery', 'Campaign gallery'), ('cover', 'Additional cover')], default='gallery', max_length=10),
        ),
    ]
