




import React, { useState } from "react";
import { BotIcon, SendIcon, SparklesIcon, DatabaseIcon } from "lucide-react";
import { PageHeader } from "../../components/ui/PageHeader";
import { DemoNotice } from "../../components/ui/DemoNotice";
import { inputClass } from "../../components/ui/Field";

type ChatMessage = {id: string;role: "assistant" | "user";text: string;cite?: string;};

const seed: ChatMessage[] = [
{ id: "m1", role: "assistant", text: "I can summarize campaign performance, allocation trends, and pending reviews. What do you need?" },
{ id: "m2", role: "user", text: "Which campaigns are pending review?" },
{ id: "m3", role: "assistant", text: "Two campaigns are pending review: Safe Housing Program (CMP-26-052) and Monsoon Relief Coalition. Youth Literacy Drive needs revision.", cite: "Source: review queue · updated today" }];


const suggestions = ["Summarize this month's inflow", "Flag campaigns below 80% allocation", "Which disclosures are due?"];

export function AdminAssistant() {
  const [messages, setMessages] = useState<ChatMessage[]>(seed);
  const [draft, setDraft] = useState("");

  function send(text: string) {
    if (!text.trim()) return;
    setMessages((prev) => [
    ...prev,
    { id: `u-${Date.now()}`, role: "user", text },
    { id: `a-${Date.now()}`, role: "assistant", text: "This is a demonstration assistant. A live version would answer from Givera's operational data with cited references.", cite: "Source: demonstration data" }]
    );
    setDraft("");
  }

  return (
    <div className="flex flex-col">
      <PageHeader eyebrow="Assistant" title="AI operations assistant" description="Query platform data in natural language." />
      <div className="mt-5 max-w-3xl"><DemoNotice>This assistant is a static demonstration. Responses are illustrative and not generated by a live model.</DemoNotice></div>

      <div className="mt-5 max-w-3xl space-y-4 rounded-lg border border-[#d8d8d2] bg-white p-5">
        {messages.map((m) =>
        <div key={m.id} className={`flex gap-3 ${m.role === "user" ? "flex-row-reverse" : ""}`}>
            <span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full ${m.role === "assistant" ? "bg-[#f0f8f4] text-[#16734e]" : "bg-[#eef2f6] text-[#3d5670]"}`}>
              {m.role === "assistant" ? <BotIcon className="h-4 w-4" aria-hidden="true" /> : <span className="text-[11px] font-bold">You</span>}
            </span>
            <div className={`max-w-[80%] rounded-lg px-3.5 py-2.5 text-[13px] leading-5 ${m.role === "assistant" ? "bg-[#f6f6f3] text-[#2b332e]" : "bg-[#16734e] text-white"}`}>
              <p>{m.text}</p>
              {m.cite ? <p className="mt-1.5 flex items-center gap-1 text-[11px] font-medium text-[#83877f]"><DatabaseIcon className="h-3 w-3" aria-hidden="true" /> {m.cite}</p> : null}
            </div>
          </div>
        )}
      </div>

      <div className="mt-4 flex max-w-3xl flex-wrap gap-2">
        {suggestions.map((s) =>
        <button key={s} type="button" onClick={() => send(s)} className="inline-flex items-center gap-1.5 rounded-full border border-[#cfd1ca] bg-white px-3 py-1.5 text-[12px] font-medium text-[#4a504a] transition-colors hover:bg-[#f5f6f3] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#16734e]">
            <SparklesIcon className="h-3.5 w-3.5 text-[#16734e]" aria-hidden="true" /> {s}
          </button>
        )}
      </div>

      <form className="mt-4 flex max-w-3xl gap-2" onSubmit={(e) => {e.preventDefault();send(draft);}}>
        <input value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Ask about operations…" aria-label="Message" className={inputClass} />
        <button type="submit" className="inline-flex shrink-0 items-center gap-2 rounded-md bg-[#16734e] px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-[#125f40] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#16734e]">
          <SendIcon className="h-4 w-4" aria-hidden="true" /> Send
        </button>
      </form>
    </div>);

}